// <auto-generated />
using System;
using MHMSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MHMSystem.Migrations.ApplicationDbContextForMarriageHallMigrations
{
    [DbContext(typeof(ApplicationDbContextForMarriageHall))]
    [Migration("20200301144223_addMarriageHallToDb")]
    partial class addMarriageHallToDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("MHMSystem.Models.MarriageHall", b =>
                {
                    b.Property<int>("hallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("bookedFromDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("bookedToDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("hallAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("hallName")
                        .HasColumnType("TEXT");

                    b.HasKey("hallId");

                    b.ToTable("MarriageHall");
                });
#pragma warning restore 612, 618
        }
    }
}
