// <auto-generated />
using MHMSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MHMSystem.Migrations.ApplicationDbContextForHallBookingDatesMigrations
{
    [DbContext(typeof(ApplicationDbContextForHallBookingDates))]
    partial class ApplicationDbContextForHallBookingDatesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("MHMSystem.Models.HallBookingDates", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("fromDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("hallId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("hallName")
                        .HasColumnType("TEXT");

                    b.Property<string>("toDate")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("HallBookingDates");
                });
#pragma warning restore 612, 618
        }
    }
}
