// <auto-generated />
using System;
using MHMSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MHMSystem.Migrations.ApplicationDbContextForBookingsMigrations
{
    [DbContext(typeof(ApplicationDbContextForBookings))]
    [Migration("20200301131036_addBookingsToDb")]
    partial class addBookingsToDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("MHMSystem.Models.Bookings", b =>
                {
                    b.Property<int>("bookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("bookingHallname")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("fromDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("hallId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("toDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("userId")
                        .HasColumnType("INTEGER");

                    b.HasKey("bookingId");

                    b.ToTable("bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
